services:

  shegroup.download.factory.database_factory:
    class: SheGroup\DownloadBundle\Factory\DatabaseFactory
    arguments: ['%shegroup.download.database.remote%','%shegroup.download.database.local%']

  shegroup.download.factory.directory_factory:
    class: SheGroup\DownloadBundle\Factory\DirectoryFactory
    arguments: ['%shegroup.download.directories%']

  shegroup.download.model.database.remote:
    class: SheGroup\DownloadBundle\Model\Database
    factory: 'shegroup.download.factory.database_factory:getRemote'

  shegroup.download.model.database.local:
    class: SheGroup\DownloadBundle\Model\Database
    factory: 'shegroup.download.factory.database_factory:getLocal'

  shegroup.download.model.directories:
    class: SheGroup\DownloadBundle\Model\Database
    factory: 'shegroup.download.factory.directory_factory:getDirectories'

  shegroup.download.handler.database_handler:
    public: true
    class: SheGroup\DownloadBundle\Handler\DatabaseHandler
    arguments:
      - '%shegroup.download.user%'
      - '%shegroup.download.host%'
      - '@shegroup.download.model.database.remote'
      - '@shegroup.download.model.database.local'
      - '%shegroup.download.database.directory%'
      - '%shegroup.download.database.max_local_db%'
      - '%shegroup.download.database.only_structure%'
    calls:
      - ['setLogger', ['@logger']]
      - ['setDefaultTimeout', ['%shegroup.download.timeout%']]

  shegroup.download.handler.directory_handler:
    public: true
    class: SheGroup\DownloadBundle\Handler\DirectoryHandler
    arguments:
      - '%shegroup.download.user%'
      - '%shegroup.download.host%'
      - '@shegroup.download.model.directories'
    calls:
      - ['setLogger', ['@logger']]
      - ['setDefaultTimeout', ['%shegroup.download.timeout%']]

  shegroup.download.command.download_command:
    class: 'Desarrolla2\DownloadBundle\Command\DownloadCommand'
    calls:
      - ['setContainer', ['@service_container']]
    tags:
      - { name: 'console.command' }

  shegroup.download.command.load_command:
    class: 'Desarrolla2\DownloadBundle\Command\LoadCommand'
    calls:
      - ['setContainer', ['@service_container']]
    tags:
      - { name: 'console.command' }

  shegroup.download.command.clean_command:
    class: 'Desarrolla2\DownloadBundle\Command\CleanCommand'
    calls:
      - ['setContainer', ['@service_container']]
    tags:
      - { name: 'console.command' }